package cn.liupengstudy.ordworld.mapper;

import cn.liupengstudy.ordworld.pojo.Conservator;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ConservatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conservator
     *
     * @mbg.generated Tue Apr 07 18:13:39 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conservator
     *
     * @mbg.generated Tue Apr 07 18:13:39 CST 2020
     */
    int insert(Conservator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conservator
     *
     * @mbg.generated Tue Apr 07 18:13:39 CST 2020
     */
    int insertSelective(Conservator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conservator
     *
     * @mbg.generated Tue Apr 07 18:13:39 CST 2020
     */
    Conservator selectByPrimaryKey(Integer id);


    List<Conservator> selectByPhoneNumber(String phoneNumber);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conservator
     *
     * @mbg.generated Tue Apr 07 18:13:39 CST 2020
     */
    int updateByPrimaryKeySelective(Conservator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conservator
     *
     * @mbg.generated Tue Apr 07 18:13:39 CST 2020
     */
    int updateByPrimaryKey(Conservator record);
}