package cn.liupengstudy.ordworld.mapper;

import cn.liupengstudy.ordworld.pojo.ProfessionalInformation;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ProfessionalInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int insert(ProfessionalInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int insertSelective(ProfessionalInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    ProfessionalInformation selectByPrimaryKey(Integer id);

    ProfessionalInformation selectByNumber(String number);

    List<ProfessionalInformation> getAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int updateByPrimaryKeySelective(ProfessionalInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int updateByPrimaryKey(ProfessionalInformation record);
}