package cn.liupengstudy.ordworld.mapper;

import cn.liupengstudy.ordworld.pojo.SystemInformation;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SystemInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int insert(SystemInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int insertSelective(SystemInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    SystemInformation selectByPrimaryKey(Integer id);

    List<SystemInformation> getAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int updateByPrimaryKeySelective(SystemInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int updateByPrimaryKey(SystemInformation record);
}