package cn.liupengstudy.ordworld.serviceInterface;

import cn.liupengstudy.ordworld.pojo.SystemInformation;

import java.util.List;

/**
 * @文件名 cn.liupengstudy.ordworld.serviceInterface
 * @描述
 * @创建人 liupeng
 * @作者联系方式 LIUPENG.0@outlook.com
 * @创建时间 2020/4/8 - 2:18 下午
 * @修改人和其它信息
 */
public interface SystemInformationInterface {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int insert(SystemInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int insertSelective(SystemInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    SystemInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int updateByPrimaryKeySelective(SystemInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    int updateByPrimaryKey(SystemInformation record);

    List<SystemInformation> getAll();
}
