package cn.liupengstudy.ordworld.pojo;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

@ApiModel(value = "专业信息")
public class ProfessionalInformation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionalInformation.id
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    @ApiModelProperty(value = "ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionalInformation.number
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    @ApiModelProperty(value = "编号")
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionalInformation.college
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    @ApiModelProperty(value = "学院")
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionalInformation.department
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    @ApiModelProperty(value = "系")
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionalInformation.professional
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    @ApiModelProperty(value = "专业")
    private String professional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    @ApiModelProperty(value = "serialVersionUID")
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionalInformation.id
     *
     * @return the value of professionalInformation.id
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionalInformation.id
     *
     * @param id the value for professionalInformation.id
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionalInformation.number
     *
     * @return the value of professionalInformation.number
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionalInformation.number
     *
     * @param number the value for professionalInformation.number
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionalInformation.college
     *
     * @return the value of professionalInformation.college
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionalInformation.college
     *
     * @param college the value for professionalInformation.college
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionalInformation.department
     *
     * @return the value of professionalInformation.department
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionalInformation.department
     *
     * @param department the value for professionalInformation.department
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionalInformation.professional
     *
     * @return the value of professionalInformation.professional
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public String getProfessional() {
        return professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionalInformation.professional
     *
     * @param professional the value for professionalInformation.professional
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    public void setProfessional(String professional) {
        this.professional = professional == null ? null : professional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", number=").append(number);
        sb.append(", college=").append(college);
        sb.append(", department=").append(department);
        sb.append(", professional=").append(professional);
        sb.append("]");
        return sb.toString();
    }
}