package cn.liupengstudy.ordworld.pojo;

import io.swagger.annotations.ApiModel;

import java.io.Serializable;

@ApiModel(value = "系统公告实体")
public class SystemInformation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemInformation.id
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemInformation.authorId
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    private Integer authorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemInformation.title
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemInformation.lpcontent
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    private String lpcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemInformation.lpyear
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    private Integer lpyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemInformation.lpmonth
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    private Integer lpmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemInformation.lpday
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    private Integer lpday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemInformation.id
     *
     * @return the value of systemInformation.id
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemInformation.id
     *
     * @param id the value for systemInformation.id
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemInformation.authorId
     *
     * @return the value of systemInformation.authorId
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemInformation.authorId
     *
     * @param authorid the value for systemInformation.authorId
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemInformation.title
     *
     * @return the value of systemInformation.title
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemInformation.title
     *
     * @param title the value for systemInformation.title
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemInformation.lpcontent
     *
     * @return the value of systemInformation.lpcontent
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public String getLpcontent() {
        return lpcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemInformation.lpcontent
     *
     * @param lpcontent the value for systemInformation.lpcontent
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public void setLpcontent(String lpcontent) {
        this.lpcontent = lpcontent == null ? null : lpcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemInformation.lpyear
     *
     * @return the value of systemInformation.lpyear
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public Integer getLpyear() {
        return lpyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemInformation.lpyear
     *
     * @param lpyear the value for systemInformation.lpyear
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public void setLpyear(Integer lpyear) {
        this.lpyear = lpyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemInformation.lpmonth
     *
     * @return the value of systemInformation.lpmonth
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public Integer getLpmonth() {
        return lpmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemInformation.lpmonth
     *
     * @param lpmonth the value for systemInformation.lpmonth
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public void setLpmonth(Integer lpmonth) {
        this.lpmonth = lpmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemInformation.lpday
     *
     * @return the value of systemInformation.lpday
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public Integer getLpday() {
        return lpday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemInformation.lpday
     *
     * @param lpday the value for systemInformation.lpday
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    public void setLpday(Integer lpday) {
        this.lpday = lpday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemInformation
     *
     * @mbg.generated Wed Apr 08 14:01:03 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", authorid=").append(authorid);
        sb.append(", title=").append(title);
        sb.append(", lpcontent=").append(lpcontent);
        sb.append(", lpyear=").append(lpyear);
        sb.append(", lpmonth=").append(lpmonth);
        sb.append(", lpday=").append(lpday);
        sb.append("]");
        return sb.toString();
    }
}