package cn.liupengstudy.ordworld.service;

import cn.liupengstudy.ordworld.entity.ProfessionalInformation;

import java.util.List;

/**
 * @文件名 cn.liupengstudy.ordworld.serviceInterface
 * @描述
 * @创建人 liupeng
 * @作者联系方式 LIUPENG.0@outlook.com
 * @创建时间 2020/4/8 - 9:08 下午
 * @修改人和其它信息
 */
public interface ProfessionallninformationInterface {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int insert(ProfessionalInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int insertSelective(ProfessionalInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    ProfessionalInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int updateByPrimaryKeySelective(ProfessionalInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professionalInformation
     *
     * @mbg.generated Wed Apr 08 21:03:38 CST 2020
     */
    int updateByPrimaryKey(ProfessionalInformation record);


    ProfessionalInformation selectByNumber(String number);

    List<ProfessionalInformation> getAll();

}
